
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftTIMESDIVnonassocUMINUSDIV LPAREN MINUS NUMBER PLUS RPAREN TIMESInicio : expr \n    expr : expr PLUS expr\n        | expr MINUS expr  \n        | expr TIMES expr\n        | expr DIV expr \n   expr : MINUS expr %prec UMINUSexpr : NUMBERexpr : LPAREN expr RPAREN'
    
_lr_action_items = {'RPAREN':([2,10,11,12,13,14,15,16,],[-7,16,-6,-5,-2,-3,-4,-8,]),'NUMBER':([0,3,5,6,7,8,9,],[2,2,2,2,2,2,2,]),'TIMES':([1,2,10,11,12,13,14,15,16,],[9,-7,9,-6,-5,9,9,-4,-8,]),'PLUS':([1,2,10,11,12,13,14,15,16,],[7,-7,7,-6,-5,-2,-3,-4,-8,]),'LPAREN':([0,3,5,6,7,8,9,],[3,3,3,3,3,3,3,]),'DIV':([1,2,10,11,12,13,14,15,16,],[6,-7,6,-6,-5,6,6,-4,-8,]),'MINUS':([0,1,2,3,5,6,7,8,9,10,11,12,13,14,15,16,],[5,8,-7,5,5,5,5,5,5,8,-6,-5,-2,-3,-4,-8,]),'$end':([1,2,4,11,12,13,14,15,16,],[-1,-7,0,-6,-5,-2,-3,-4,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,3,5,6,7,8,9,],[1,10,11,12,13,14,15,]),'Inicio':([0,],[4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Inicio","S'",1,None,None,None),
  ('Inicio -> expr','Inicio',1,'p_inicio','gramatica.py',45),
  ('expr -> expr PLUS expr','expr',3,'p_operaciones','gramatica.py',54),
  ('expr -> expr MINUS expr','expr',3,'p_operaciones','gramatica.py',55),
  ('expr -> expr TIMES expr','expr',3,'p_operaciones','gramatica.py',56),
  ('expr -> expr DIV expr','expr',3,'p_operaciones','gramatica.py',57),
  ('expr -> MINUS expr','expr',2,'p_expr2uminus','gramatica.py',100),
  ('expr -> NUMBER','expr',1,'p_expr2NUM','gramatica.py',113),
  ('expr -> LPAREN expr RPAREN','expr',3,'p_parens','gramatica.py',124),
]
